### ISSUE TITLE
افزودن امکان انتخاب قلم و فهرست‌کردن قلم‌های موجود به نرم‌افزار آراسته

### ISSUE THREAD

**Issue by ghost** [ekm507/araste#13]
در برنامه ی figlet فونت مورد نظر رو با این دستور انتخاب میکنیم : 
````
figlet -f {font}
````
ایا منظور شما از **_امکان انتخاب قلم و فهرست کردن قلم های موجود_** همین هست ؟

**Comment by ekm507** [comment]
سلام!
بله! کاربر باید بتواند اسم قلم یا آدرس قلم را به برنامه بدهد.
احتمالاً از کتاب‌خانهٔ argparse پایتون برای دریافت آرگومان‌ها استفاده کنم.

**Comment by ghost** [comment]
درست .
من هم روی این بخش کار خواهم کرد .

**Comment by ekm507** [comment]
بسیار خب.
پس بهتر است برای جلوگیری از conflict من روی این کار نکنم.

**Comment by ghost** [comment]
درود چند روزی روی پروژه های دیگه ام کار میکردم نتونستم پیگیر بشم ! ( از یادم رفت پوش کنم )
امروز این موضوع رو حل کردم .

**Comment by ekm507** [comment]
درود!
بابت PRها سپاسگزارم!
همه‌شون ادغام شدند. البته چند اصلاح روی آن‌ها اعمال کردم.

**Comment by ekm507** [comment]
برای این که این ابزار شبیه ابزار figlet باشد، دو ویژگی به آن افزوده خواهد شد:

۱. برای نوشتن نوشته، نیازی به گذاشتن سوییچ -t نباشد.
۲. وقتی نوشته به‌عنوان آرگومان برنامه داده نشود، از ورودی استاندارد دریافت خواهد شد.

احتمالاً هر دوی این‌ها رو به‌زودی انجام بدهم.

بعد از افزودن این دو ویژگی می‌توانیم این ایشو را ببندیم.

**Comment by ghost** [comment]
درود .
خواهش میکنم . 
من هم میتونستم انجام بدم اما هدف داشتم !
دقت کردید زمانی که با گیت کامیتی رو انجام میدیم از سوییچ -m استفاده میکنیم ؟ اینجا با فلگ -t انجام شد.
اما یک خلاقیتی بود که کاملا متشابه یک ابزار دیگه نباشد .
با تشکر :)

**Comment by ekm507** [comment]
والا بهتره ابزار شبیه toilet باشه چون همه باهاش آشنایی دارند و استفاده ازش راحته. شبیه بیشتر ابزارهای یونیکسی مرسومه و از قبل می‌دونی چطوری باید ازش استفاده کنی!

>  دقت کردید زمانی که با گیت کامیتی رو انجام میدیم از سوییچ -m استفاده میکنیم ؟ اینجا با فلگ -t انجام شد.

آره! ولی دلیلش اینه که جلوی git commit ورودی دیگری می‌گیره که معمولاً نمی‌دی. یعنی ورودی اصلی این دستور چیز دیگری است که متن کامیت نیست. آرگومان این دستور چیزی به اسم pathspec است که آدرس یک فایل مربوط به کامیت رو قبول می‌کنه.
در این برنامهٔ ما آرگومان اصلی برنامه دقیقاً همون نوشته است.

>  با تشکر :)

سپاس از شما :heart: 

یک پول ریکوئست دادم.
