### ISSUE TITLE
پیش‌نمایش خروجی برنامه در موبایل به‌درستی دیده نمی‌شود

### ISSUE THREAD

**Issue by ekm507** [ekm507/araste#16]
پیش‌نمایش خروجی برنامه که در فایل README.md قرار دارد و با قلم monospace است، در بعضی از مرورگرهای موبایل به‌درستی دیده نمی‌شود.
به‌نظرم می‌توانیم یک عکس را نیز در کنار متن قرار دهیم تا همه بتوانند خروجی برنامه را همان‌طور که هست ببینند.
پیشنهاد شما چیست؟ آیا موافقید؟

**Comment by ghost** [comment]
دقیقا منظور شما چی هست ؟
من در موبایل مشکل خواصی مشاهده نمیکنم .
در ضمن این موضوع خیلی هم اهمین زیادی ندارد .
و فقط اتلاف زمان هست . این برنامه تنها روی دسکتاب و روی سیستم های unix base قابلیت اجرا شدن دارد .

**Comment by ekm507** [comment]
بعضی از مرورگرها و نرم‌افزارهای موبایل نوشتهٔ monospace را در صفحات وب به‌درستی نمایش نمی‌دهند. از جمله opera و نرم‌افزار telegram
برای معرفی این نرم‌افزار در گروه‌های تلگرامی لازم می‌دونم که تصویر هم افزوده بشه. چون خیلی‌ها با موبایل پیوندها رو باز می‌کنند.
بله این برنامه تنها برای میزکار است ولی برای آشنایی با برنامه شما می‌تونید از موبایل استفاده کنید.
اگر نکتهٔ دیگری دارید بفرمایید.
من می‌خواهم این تصویر رو به ابتدای فایل README اضافه کنم. مثل یک بنر. نظر شما چیست؟
![image](https://user-images.githubusercontent.com/13185969/178108137-33dc9e58-f1e9-4c17-8de2-3274634988f3.png)

**Comment by ghost** [comment]
خیلی خب از این دیدگاه ایده ی بدی نیست .
ولی اگر امکان دارد زیر این متن این عکس رو قرار بدید : 

 تبدیل نوشته‌های فارسی به هنر اسکی 

به طوری که وسط چین باشد.
