### ISSUE TITLE
English README

### ISSUE THREAD

**Issue by ghost** [ekm507/araste#17]
در این ایشو میخواستم بگم من روی این قسمت دارم کار میکنم . و اینکه english readme رو در فایلی به نام README_EN.md قرار دادم . ایا نظر دیگه ای دارید ؟

**Comment by ekm507** [comment]
عه؟
باشه پس من بیخیال می‌شم :))
نه نکته‌ای نیست. فقط این که در فایل انگلیسی بنویس که این هم برای عربی و هم برای فارسی است.
سپاسگزارم.

**Comment by ghost** [comment]
حله . پول میدم .

**Comment by ghost** [comment]
خوب بود ؟

**Comment by ekm507** [comment]
بله. همون موقع بازبینی و ادغام کردم.
