### ISSUE TITLE
TODOS.md

### ISSUE THREAD

**Issue by ghost** [ekm507/araste#19]
این یک پیشنهاد است :
به نظر من میتونیم todo های پروژه رو در یک فایلی به نام todos.md یا به شکل انگلیسی یا فارسی ( تفاوتی ندارد ) قرار بدیم تا readme شلوغ نشود .

**Comment by ghost** [comment]
با سلام .
میخواستم بدونم که به هرحال موافق هستید یا خیر ؟ todo هارو مرتب کنم ؟
من پول میدم اگر خواستی قبول کن .

**Comment by ekm507** [comment]
مرج شد.
