### ISSUE TITLE
استاندارد پایتون

### ISSUE THREAD

**Issue by shmf1385** [ekm507/araste#24]
سلام.
اسکریپت های پایتون معمولا از استاندارد خاصی پیروی می‌کنند که امکان قرار دادن اسکریپت در pypi را می‌دهد.
می‌توانم آن استاندارد را روی آراسته اجرا کنم؟

**Comment by ekm507** [comment]
سلام!
از ایجاد این بحث سپاسگزارم!
یعنی مثل یک کتابخانه قابل استفاده باشد؟ این اتفاق خوبی خواهد بود.
فقط روی فایل آراسته، @smsameet  هم می‌خواست [کارهایی](https://github.com/ekm507/araste/issues/13) بکند.
برای جلوگیری از ایجاد تعارض (conflict) هنگام مرج گفتم.
هم‌چنین هر کاری لازمه بگو تا من انجام دهم.

**Comment by shmf1385** [comment]
خب پس من صبر می‌کنم تا کار @smsameet تمام شود. چون کاری که می‌خواهم انجام دهم تقریبا با ریشهٔ برنامه کار دارد

**Comment by ekm507** [comment]
کارهای اصلی برنامه تمام شده.
الان می‌تونی هر کاری دوست داشتی انجام بدی.

اگر تغییر خاصی در نظر داری بگو تا من اعمال کنم.

**Comment by ekm507** [comment]
در [این‌جا](https://github.com/ekm507/araste/pull/44#issue-1307004832) ادغام شد.
سپاسگزارم!
