### ISSUE TITLE
پیشنهاد: Package + pypi

### ISSUE THREAD

**Issue by momansoury** [ekm507/araste#34]
باسلام
    درصورت مقدور اسکریپت رو پکیج کرده و در pypi قرار دهید تا بتونیم راحتتر نصب کنیم

**Comment by ekm507** [comment]
سلام!
از باز کردن این موضوع سپاسگزارم.
یک ایشو با این موضوع وجود دارد و این کار [این‌جا](https://github.com/ekm507/araste/issues/24#issue-1300583659) درحال بررسی است.
پس من این ایشو را به‌دلیل تکراری‌بودن می‌بندم.  :heart:
