### ISSUE TITLE
 جایگزینی print داخل آراسته به‌نحوی که بتواند داخل یک رشته هم چاپ کند و آراسته مثل یک کتاب‌خانه قابل‌استفاده باشد.

### ISSUE THREAD

**Issue by ghost** [ekm507/araste#43]
درود !
اگر میشه دقیق تر این موضوع رو بیان کنید .
منظور شما از این todo دقیقا چی هستش ؟

**Comment by ekm507** [comment]
سلام!
منظور این است که بتوان از آراسته مثل یک کتاب‌خانه در برنامه‌های دیگر استفاده کرد.
در این صورت خروجی برنامه به‌جای چاپ در ترمینال، در یک رشته (string) ریخته می‌شود و می‌توان از آن در برنامه‌های دیگر هر استفاده‌ای کرد.
احتمالاً الان برای این کار زود است.
این را پس از بازنویسی بخش‌هایی از برنامه انجام خواهم داد. باید عملکردهایی مثل خواندن قلم یا گرفتن ورودی تبدیل به تابع شوند.

**Comment by ghost** [comment]
روی این بخش کار کنم ؟
`عملکردهایی مثل خواندن قلم یا گرفتن ورودی تبدیل به تابع شوند. `

**Comment by shmf1385** [comment]
من این امکان رو در درخواست ادغام شمارهٔ https://github.com/ekm507/araste/pull/44 اضافه کردم

**Comment by ekm507** [comment]
سپاسگزارم!

> روی این بخش کار کنم ؟ `عملکردهایی مثل خواندن قلم یا گرفتن ورودی تبدیل به تابع شوند. `

می‌خواستم خودم انجامش بدهم ولی خب  اگر تمایل داری می‌تونی انجامش بدهی. هر کجا که سؤال داشتی از من بپرس!

> من این امکان رو در درخواست ادغام شمارهٔ #44 اضافه کردم

منظور چیز دیگری است.
منظور این است که برنامهٔ araste.py به‌جای چاپ در ترمینال، خروجی‌اش را داخل یک رشته قرار دهد و کار چاپ را تابع دیگری برعهده بگیرد.

**Comment by ekm507** [comment]
خب! من این مورد رو در کامیت بزرگ 93c0da5e9bb491605c3c2c1371c0e54867758ae8 انجام دادم!
الان از تابع render آراسته می‌شه داخل یک برنامهٔ پایتون استفاده کرد. این تابع به‌جای چاپ خروجی در پایانه، اون رو به شکل رشته برمی‌گردونه. وظیفهٔ چاپ خروجی بر عهدهٔ فایل اجرایی araste گذاشته شده.
تغییرات زیادی بود ولی چون همه باهم بودند فقط یک کامیت شد.
