### ISSUE TITLE
کرش کردن برنامه

### ISSUE THREAD

**Issue by ghost** [ekm507/araste#53]
درود !
میخواستم بدونم که چرا در این قسمت از برنامه ( داخل پوشه ی araste و فایل araste.py ) باید برنامه raise بکنه ؟ احتمالا بهتر نیست بهش خودمون خطا بدیم تا اینکه کاربر یک ارور پایتونی مشاهده کنه ؟

    fonts_dir = __file__.replace("araste.py", "") + "fonts"
    font_filename = fonts_dir.rstrip(
        '/') + '/' + font.replace(".flf", "") + ".flf"
    try:
        fontFile = open(font_filename)
        flf_headers = fontFile.readline().split(' ')
    except:
        raise FileNotFoundError`

**Comment by ekm507** [comment]
سلام!
اگر خطایی هست بگو چه‌طوری می‌تونم این خطا رو بازسازی کنم؟
وگرنه اگر پیشنهادی داری کامیت کن :)

**Comment by ghost** [comment]
نه ! برنامه کرش نکرده .
منطورم این بود که دلیلی داره که اینجا raise شده ؟ چرا مسیجی چیزی نبود ؟

**Comment by shmf1385** [comment]
این کد رو من نوشتم
باید خطا توی اسکریپت `araste` گرفته بشه و تبیدل به پیام بشه

**Comment by ekm507** [comment]
> این کد رو من نوشتم باید خطا توی اسکریپت `araste` گرفته بشه و تبیدل به پیام بشه

طبق آخرین پیام، این موضوع را می‌توانیم ببندیم.
برای بررسی پیام‌های خطا می‌توان ایشوی دیگری باز کرد.
