### ISSUE TITLE
نسخهٔ ۱.۲

### ISSUE THREAD

**Issue by ekm507** [ekm507/araste#58]
سلام!
برای انتشار نسخهٔ ۱.۲ رسیدن به چه اهدافی را پیشنهاد می‌کنید؟
پیشنهادهای من:
- داشتن ۴ قلم (انجام شده)
- اضافه شدن اعداد و علایم نگارشی ضروری مثل نقطه به قلم‌ها

**Comment by nimafanniasl** [comment]
اضافه شدن امکان استفاده از مخزن های مختلف به araste-get

**Comment by ekm507** [comment]
درحال حاضر این امکان‌ها افزوده شده‌اند:

- قلم‌های بیشتر (تعدادی از قلم‌های موجود در مخزن araste-fonts کامل شده‌اند و امکان افزودن به مخزن خود آراسته را دارند)
- پشتیبانی برخی از قلم‌ها از عددها و علایم نگارشی فارسی (قلم‌ها باید به این مخزن انتقال پیدا کنند)
- ویژگی جدید: امکان خروجی رنگی (در انتشار بعدی می‌توانیم جهت تغییر رنگ‌ها را هم اضافه کنیم)
- ویژگی جدید: امکان انتخاب جهت متن (چپ‌چین، راست‌چین، وسط‌چین)

**Comment by ekm507** [comment]
برای انتشار بعدی مشکل داریم و اون ناسازگاری بسته‌بندی آرچ با pip است. در بخش‌هایی از برنامهٔ پایتون که آدرس‌دهی به محل فایل‌ها رو داریم.
با توجه به این که آراسته در هفتهٔ گذشته فعالیتی نداشته است، من با اجازه بسته‌بندی pip رو می‌سازم و نسخهٔ ۱.۲ رو منتشر می‌کنم.

**Comment by nimafanniasl** [comment]
خب دیگه اینجا کاری نمومنده، فکر کنم باید بسته شه :)
