### ISSUE TITLE
بارگیری چند قلم با یک دستور

### ISSUE THREAD

**Issue by shmf1385** [ekm507/araste#71]
سلام.
من قابلیت بارگیری چند قلم با یک دستور رو اضافه کردم
یعنی اگه اسم قلم‌ها رو پشت سر هم به `araste-get` بگیم بره همه‌شون رو بارگیری کنه
فقط تنها مسئله اینه که باید یه جوری به argparse این رو بهفمونیم که چندتا رو قبول کنه
الان خطا میده
در صورتی که توابع بارگیری و حذف هر دو درست کار می‌کنند.
شما روشش را بلدید؟
![image](https://user-images.githubusercontent.com/60741415/181925141-a1afc212-dc09-4155-b2f3-335dd41a8182.png)

**Comment by ekm507** [comment]
سلام!
فایلی که توش تغییر داده‌ای رو پیدا نکردم.
درعوض من تغییری دادم که الان کار می‌کنه. منتها خیلی سریع انجام دادم.
پس بی‌زحمت خودت اون رو جوری که فکر می‌کنی خوبه تغییرش بده و بعد پول‌ریکوئست بزن.
فایل رو همین‌جا می‌فرستم.
[araste-get.txt](https://github.com/ekm507/araste/files/9227120/araste-get.txt)

**Comment by shmf1385** [comment]
تشکر
مشکل از همون nargs بود که باید برابر با "*" باشد
