### ISSUE TITLE
نگارش ۱.۳

### ISSUE THREAD

**Issue by ekm507** [ekm507/araste#73]
ویژگی‌هایی که در نگارش بعدی خواهند بود:

- اضافه شدن امکان استفاده از آراسته در برنامه‌های پایتونی دیگر
- اضافه شدن امکان تعیین پهنای متن
- اضافه شدن امکان بارگیری، به‌روزرسانی و حذف چند قلم باهم به مدیر قلم آراسته (araste-font)
- اضافه شدن یک man page (هنوز انجام نشده ولی در دست انجام است.)
- معرفی فیلترها: امکان توسعهٔ سریع‌تر جلوه‌ها
- افزودن ۲ فیلتر رنگین‌کمان با طرح‌های جدید
- فیلتر جدید: قاب‌کردن خروجی با یک جعبه
- فیلتر جدید: آینه‌کردن خروجی (افقی و عمودی) و چرخش ۹۰ درجه
- فیلتر جدید: متن ایتالیک
- فیلتر جدید: بزرگ‌تر کردن متن (در جهت‌های افقی و عمودی)
- فیلتر جدید: خروجی فقط با یک رنگ (قرمز، نارنجی، زرد، سبز، فیروزه‌ای، آبی، بنفش)
ویژگی‌های دیگری که به نظر شما باید باشند را بگویید!

**Comment by shmf1385** [comment]
چاپ متن فقط با یک رنگ(سعی می‌کنم رویش کار کنم)

**Comment by ekm507** [comment]
> چاپ متن فقط با یک رنگ(سعی می‌کنم رویش کار کنم)

ایدهٔ جالبیه. دربارهٔ پیاده‌سازی این یک ایده داشتم و اون رو الان به یک ایشوی دیگر منتقل کردم. یعنی این‌جا: https://github.com/ekm507/araste/issues/75
لطفاً قبل از ساختن، روش جدید اعمال فیلترها رو ببین.

ویرایش:
 فیلتری که می‌خواستی رو افزودم. در واقع فیلترهای زیر:
`red, orange, yellow, green, cyan, blue, purple`
البته مطمئن نیستم که رنگ درستی رو چاپ می‌کنند یا نه! چون بسته به زمینهٔ رنگی پایانه، این رنگ‌ها هم متفاوت دیده می‌شوند. (terminal color theme)

**Comment by ekm507** [comment]
نگارش جدید را منتشر کردم.
موردی که در این نگارش نتوانستم اضافه کنم: «صفحهٔ راهنمای man page». درواقع این صفحه ساخته شده است اما نتوانستم آن را به بسته‌بندی اضافه کنم.
همچنین بسته‌بندی آرچ نیز انجام نشده است.
