### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by nimafanniasl** [ekm507/araste#90]
سلام.
وقتی آراسته با pipx نصب میشه، requests نصب نمیشه و در نتیجه araste-get کار نمیکنه.
فکر کنم مشکل همون مشکلیه که در #84 گفته شده. بنظرم باید زود حل شه و نسخه 3.2 آراسته منتشر بشه.

**Comment by nimafanniasl** [comment]
#91

**Comment by ekm507** [comment]
درخواستتون ادغام شد.

**Comment by nimafanniasl** [comment]
به pypi اضافه شده؟ چون هنوز هم این مشکل وجود داره!

**Comment by ekm507** [comment]
آره افزوده بودم. هنوز هم همون خطا رو می‌ده؟
نیازمندی argparse رو حذف کردم راستی. نکنه مشکل از اونه؟

**Comment by nimafanniasl** [comment]
سلام. مشکل حل شده. این پیام رو قبل از اینکه نسخه 3.2 بیاد فرستاده بودم (:
